#This Makefile created by makeMakefile.pl


all :
	$(MAKE) -f ../Makefile TOP=../../.. T_A=win32-x86-mingw  $@

.DEFAULT: force
	$(MAKE) -f ../Makefile TOP=../../.. T_A=win32-x86-mingw  $@

force:  ;
